CREATE TABLE [dbo].[Characters] (
    [Id]                      INT            IDENTITY (1, 1) NOT NULL,
    [Name]                    NVARCHAR (50)  NOT NULL,
    [OwnerId]                 NVARCHAR (128) NOT NULL,
    [Body]                    INT            NULL,
    [Agility]                 INT            NULL,
    [Reaction]                INT            NULL,
    [Strength]                INT            NULL,
    [Willpower]               INT            NULL,
    [Logic]                   INT            NULL,
    [Intuition]               INT            NULL,
    [Charisma]                INT            NULL,
    [Edge]                    INT            NULL,
    [PhysicalInitiativeBonus] INT            NULL,
    [PhysicalInitiativeDice]  INT            NULL,
    [AstalInitiativeBonus]    INT            NULL,
    [AstalInitiativeDice]     INT            NULL,
    [MatrixInitiativeBonus]   INT            NULL,
    [MatrixInitiativeDice]    INT            NULL,
    [PhysicalTrackBonus]      INT            NULL,
    [StunTrackBonus]          INT            NULL,
    [PhysicalTrackOffset]     INT            NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC), 
    CONSTRAINT [FK_Characters_Users] FOREIGN KEY ([OwnerId]) REFERENCES [AspNetUsers]([Id]),
);


